# Site settings
title: "Rafael Rios Moya"
email: ganchix@gmail.com
description: "Rafael Rios Moya Personal Page"
baseurl: ""
url: "http://ganchix.github.io/"
title_description: "A computer science engineer passionate with the technology world. Born in Barcelona, actually lives in Madrid where works in Fintonic like software architect. Loves games, friends, parties and enjoy the life!"
title_image: "https://www.gravatar.com/avatar/9f067fd6236eb356c210f063cf302b28?s=500&d=mm"
google_analytics: "UA-99602534-1"
disqus_account: http-ganchix-github-io
github_repository: https://github.com/ganchix
addthis_id: ra-592170e98920269e
post_limit: 5

# Social usernames/URLs
twitter_username: ganchix
github_username:  ganchix
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/rafael-r%C3%ADos-moya-16053742/
google_plus_link:
stackoverflow_link: http://stackoverflow.com/users/2617371/ganchix
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
