# Site settings
title: Rafael Ríos's CV 
description: Rafael Rios's CV
favicon: /assets/img/avatar.JPG
url: https://ganchix.github.io/
rss_url: /pages/atom.xml
google_analytics: UA-99602534-1

# Build settings
markdown: kramdown

exclude: [vendor]

site:
  github:
    url: https://github.com/ganchix

# Author settings
author:
  name: Rafael Ríos Moya
  title: Software Architect
  address: Madrid, Sapin
  email: ganchix#gmail.com
  link:
  weibo:
  github: ganchix
  linkedin: rafael-ríos-moya-16053742
  twitter: ganchix
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
  stackoverflow: 2617371
  workHistory:
    - work1:
      company: Fintonic Servicios Financieros S.L.
      location: Madrid, Spain
      title: Software Architect
      started: 2014
      duration: (2014 - Present)
      description:
    - work2:
      company: Profile Software Service S.L.
      location: Madrid, Spain
      title: Senior Software Engineer
      started: 2013
      duration: (2013 - 2014)
      description:
    - work3:
      company: Gloin S.L.
      location: Cáceres, Spain
      title: Java Developer
      started: 2011
      duration: (2011 - 2013)
      description:
  educationHistory:
    - education1:
      organization: Extremadura University
      location: Cáceres, Spain
      degree: Bachelor
      major: Software Engineering
      started: 2006
      duration: (2006 - 2011)
      description:
  languages:
    - language1:
      name: Spanish
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: Java/Java EE
      percentage: 100%
    - skill2:
      name: Spring Framework
      percentage: 90%
    - skill3:
      name: MongoDB
      percentage: 80%
    - skill4:
      name: AngularJS
      percentage: 70%
    - skill5:
      name: Scala
      percentage: 60%
