# Site settings
title: Rafael Ríos's CV 
description: Rafael Rios's CV
favicon: /assets/img/avatar.JPG
url: https://ganchix.github.io/
rss_url: /pages/atom.xml
google_analytics: UA-99602534-1

# Build settings
markdown: kramdown

exclude: [vendor]

site:
  github:
    url: https://github.com/ganchix

# Author settings
author:
  name: Rafael Ríos Moya
  title: Software Architect
  address: Madrid, Sapin
  email: ganchix#gmail.com
  link:
  weibo:
  github: ganchix
  linkedin: rafael-ríos-moya-16053742
  twitter: ganchix
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
  stackoverflow: 2617371
  workHistory:
    - work1:
      company: Fintonic Servicios Financieros S.L.
      location: Madrid, Spain
      title: Software Architect
      started: 2014
      duration: (2014 - Present)
      description: "Development and improvement of Fintonic architecture.</br>
                   Analysis, design and implementation of software solutions.</br>
                   Maintenance and support of software.</br>
                   Thanks to my passing through Fintonic I have acquired attitudes in the following technologies:</br>
                   <ul>
                   <li>Development in Java J2EE and Scala.</li>
                   <li>Frameworks: Spring Cloud, Spring Boot, Spring Core, Spring Security, Spring MVC, Spring AMQP, Spring Data, Spring Aspect, Apache Thrift, Hibernate, MyBatis, AngularJS, Bootstrap and Jquery.</li>
                   <li>IDE: Eclipse STS and Intellij.</li>
                   <li>Testing: JUnit, Mockito and JMeter.</li>
                   <li>Application servers: Tomcat and Jetty.</li>
                   <li>RDBMS: Mysql.</li>
                   <li>Messaging system: RabbitMQ.</li>
                   <li>Cloud Services: Amazon EC2 and Amazon CloudWatch.</li>
                   <li>NoSQL: MongoDB.</li>
                   <li>Big Data Tools: Apache Spark, Logstash, Elasticsearch and Kibana.</li>
                   <li>Continuous integration and software quality: Jenkins and Sonar.</li>
                   <li>Repositories: Apache Maven, Artifactory, SVN and Git.</li>
                   <li>Other tools: Web Services (SOA and REST), Drools, Solr, JSP, JSTL, Javascript, JAX-WS, JAXB, Javascript and Agile Methodologies.</li>
                    </ul>"
    - work2:
      company: Profile Software Service S.L.
      location: Madrid, Spain
      title: Senior Software Engineer
      started: 2013
      duration: (2013 - 2014)
      description: "Analysis, design and implementation of software solutions.</br>
                    Maintenance and support of software.</br>
                    The principal client was Mutua Madrileña</br>
                    Thanks to my passing through Profile I have acquired attitudes in the following technologies:</br>
                    <ul>
                    <li>Development in Java J2EE.</li>
                    <li>Frameworks: Spring Core, Spring Security, Spring MVC, Spring Data, Hibernate, DWR and Jquery.</li>
                    <li>IDE: Rational Software 8.</li>
                    <li>Testing: JUnit, Mantis and JMeter.</li>
                    <li>Application servers: Websphere 8.</li>
                    <li>RDBMS: DB2 i 7.</li>
                    <li>Continuous integration and software quality: Jenkins and Sonar.</li>
                    <li>Repositories: Apache Maven and SVN.</li>
                    <li>Other tools: Web Services (SOA and REST), JSP, JSTL, UML, WebSphere eXtreme Scale, Javascript, LDAP, JAX-WS, JAXB, Javascript and Agile Methodologies.</li>
                    </ul>"
    - work3:
      company: Gloin S.L.
      location: Cáceres, Spain
      title: Java Developer
      started: 2011
      duration: (2011 - 2013)
      description: "Analysis, design and implementation of software solutions.</br>
                   Maintenance and support of software.</br>
                   The clients were SGAE, LatinNet, Indra and University of Extremadura.</br>
                   Thanks to my passing through Gloin SL I have acquired attitudes in the following technologies:</br>
                    <ul>
                   <li>Development in Java J2EE.</li>
                   <li>Frameworks: Spring Core, Spring Security, Spring MVC, Spring Data, Spring AMQP, Hibernate and Apache CXF.</li>
                   <li>Testing: JUnit, Mantis and JMeter.</li>
                   <li>Application servers: Apache Tomcat, and Jboss.</li>
                   <li>RDBMS: Oracle Database 11g, 12g and MySQL.</li>
                   <li>Messaging system: HornetQ.</li>
                   <li>Continuous integration and software quality: Jenkins and Sonar.</li>
                   <li>Repositories: Apache Maven, SVN and Git.</li>
                   <li>Android: Spring for Android, Google Cloud Messaging, ActionBarSherlock and SlidingMenu.</li>
                   <li>Cloud Computing, knowledge of platforms Amazon, Google and Microsoft.</li>
                   <li>Other tools: BPMN, Web Services (SOA and REST), JMS, XML, Lucene, JSP, JSTL, Swing, UML and Agile methodologies.</li>
                   </ul>"
  educationHistory:
    - education1:
      organization: Extremadura University
      location: Cáceres, Spain
      degree: Bachelor
      major: Software Engineering
      started: 2006
      duration: (2006 - 2011)
      description:
  languages:
    - language1:
      name: Spanish
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: Java/Java EE
      percentage: 100%
    - skill2:
      name: Spring Framework
      percentage: 90%
    - skill3:
      name: MongoDB
      percentage: 80%
    - skill4:
      name: AngularJS
      percentage: 75%
    - skill5:
      name: Scala
      percentage: 60%
